# Generated by Django 5.2.8 on 2025-11-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recurso_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
